"""add_cryptographic_hash_to_operational_logs

Revision ID: 0f7766129bc9
Revises: 640e79871a9b
Create Date: 2026-07-13 20:53:04.713286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7766129bc9'
down_revision: Union[str, Sequence[str], None] = '640e79871a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_logs', sa.Column('cryptographic_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_logs', 'cryptographic_hash')
    # ### end Alembic commands ###
