"""Phase 17 Part 1 SLA and Tasks

Revision ID: 2e54d30570dc
Revises: 36236af4a38b
Create Date: 2026-07-01 22:51:19.756074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e54d30570dc'
down_revision: Union[str, Sequence[str], None] = '36236af4a38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_sla_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.String(length=50), nullable=False),
    sa.Column('acknowledge_within_minutes', sa.Integer(), nullable=False),
    sa.Column('resolve_within_minutes', sa.Integer(), nullable=False),
    sa.Column('escalate_to_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ADMISSION', 'VITALS_RECORDED', 'ALERT_TRIGGERED', 'RECOMMENDATION_GENERATED', 'SHADOW_RECOMMENDATION_GENERATED', 'RECOMMENDATION_APPROVED', 'RECOMMENDATION_REJECTED', 'TRANSFER_COMPLETED', name='clinicaleventtype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_role', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('baseline_spo2', sa.Integer(), nullable=True),
    sa.Column('baseline_heart_rate', sa.Integer(), nullable=True),
    sa.Column('baseline_systolic_bp', sa.Integer(), nullable=True),
    sa.Column('baseline_respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('patient_vitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('resp_rate', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('consciousness_level', sa.Enum('ALERT', 'CVPU', name='consciousnesslevel'), nullable=False),
    sa.Column('oxygen_supplement', sa.Boolean(), nullable=False),
    sa.Column('spo2_scale', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('clinical_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskband'), nullable=False),
    sa.Column('operational_priority', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['scoring_policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_escalations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('from_role', sa.String(length=50), nullable=True),
    sa.Column('to_role', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='taskstatus'), nullable=False),
    sa.Column('assigned_to_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_record_id', sa.Integer(), nullable=False),
    sa.Column('parameter_breakdown', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['score_record_id'], ['score_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('score_record_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.Enum('USEFUL', 'TOO_SENSITIVE', 'TOO_LATE', 'INCORRECT_BASELINE', 'ALREADY_REVIEWED', 'NEEDS_ESCALATION', name='feedbacktype'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_record_id'], ['score_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    from sqlalchemy.dialects import postgresql
    alertstatus = postgresql.ENUM('CREATED', 'ASSIGNED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', 'EXPIRED', 'DISMISSED', 'FALSE_ALARM', name='alertstatus')
    alertstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('alerts', sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', 'EXPIRED', 'DISMISSED', 'FALSE_ALARM', name='alertstatus'), server_default='CREATED', nullable=False))
    op.add_column('alerts', sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('assigned_to_role', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolution_note', sa.String(length=1000), nullable=True))
    op.add_column('alerts', sa.Column('sla_due_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['acknowledged_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('recommendations', sa.Column('is_shadow', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'is_shadow')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'sla_due_at')
    op.drop_column('alerts', 'resolution_note')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'resolved_by')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'assigned_to_role')
    op.drop_column('alerts', 'assigned_to_user_id')
    op.drop_column('alerts', 'status')
    op.drop_table('doctor_feedback')
    op.drop_table('score_explanations')
    op.drop_table('clinical_tasks')
    op.drop_table('alert_escalations')
    op.drop_table('score_records')
    op.drop_table('patient_vitals')
    op.drop_table('patient_baselines')
    op.drop_table('notifications')
    op.drop_table('clinical_events')
    op.drop_table('scoring_policies')
    op.drop_table('response_sla_policies')
    # ### end Alembic commands ###
