"""Add Clinical Safety Review Layer

Revision ID: 36236af4a38b
Revises: 
Create Date: 2026-07-01 16:02:39.839168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36236af4a38b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('actioned_by_user_id', sa.Integer(), nullable=True))
    op.add_column('recommendations', sa.Column('override_reason', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'recommendations', 'users', ['actioned_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'override_reason')
    op.drop_column('recommendations', 'actioned_by_user_id')
    op.drop_column('recommendations', 'expires_at')
    # ### end Alembic commands ###
