"""init

Revision ID: 466797c82558
Revises: 
Create Date: 2026-07-02 20:44:46.691990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '466797c82558'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_data', sa.String(length=2000), nullable=True),
    sa.Column('after_data', sa.String(length=2000), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='dq_issue_severity_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWED', 'RESOLVED', 'IGNORED', name='dq_issue_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('request_body_hash', sa.String(length=64), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('MANUAL', 'CSV', 'API', name='integration_type_enum'), nullable=False),
    sa.Column('mode', sa.Enum('MANUAL', 'CSV_IMPORT', 'API_READ_ONLY', name='integration_mode_enum'), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISABLED', 'MANUAL', 'CSV_READY', 'SYNCING', 'FAILED', 'READ_ONLY', name='integration_status_enum'), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_hospitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('icu_beds_available', sa.Integer(), nullable=False),
    sa.Column('general_beds_available', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('admission_reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('STABLE', 'SERIOUS', 'CRITICAL', name='patientstatus'), nullable=False),
    sa.Column('criticality_score', sa.Float(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(), nullable=False),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.Column('current_bed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_bed_id'], ['beds.id'], name='fk_patient_current_bed', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_sla_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.String(length=50), nullable=False),
    sa.Column('acknowledge_within_minutes', sa.Integer(), nullable=False),
    sa.Column('resolve_within_minutes', sa.Integer(), nullable=False),
    sa.Column('escalate_to_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'NURSE', 'COORDINATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('ICU', 'GENERAL', 'EMERGENCY', name='wardtype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('SCORE_SPIKE', 'LOW_OXYGEN', 'ICU_AT_CAPACITY', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', 'EXPIRED', 'DISMISSED', 'FALSE_ALARM', name='alertstatus'), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_role', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'CLEANING', 'RESERVED', 'MAINTENANCE', name='bedstatus'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='fk_bed_patient', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ADMISSION', 'VITALS_RECORDED', 'ALERT_TRIGGERED', 'RECOMMENDATION_GENERATED', 'SHADOW_RECOMMENDATION_GENERATED', 'RECOMMENDATION_APPROVED', 'RECOMMENDATION_REJECTED', 'TRANSFER_COMPLETED', name='clinicaleventtype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_id_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('external_patient_code', sa.String(length=200), nullable=False),
    sa.Column('internal_patient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['internal_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_id_mappings_external_patient_code'), 'external_id_mappings', ['external_patient_code'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', name='import_batch_status_enum'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('integration_name', sa.String(length=200), nullable=False),
    sa.Column('integration_type', sa.Enum('MANUAL', 'CSV', 'API', name='integration_type_enum_log'), nullable=False),
    sa.Column('mode', sa.Enum('MANUAL', 'CSV_IMPORT', 'API_READ_ONLY', name='integration_mode_enum_log'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='log_direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', name='log_status_enum'), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_success', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_idempotency_key'), 'integration_logs', ['idempotency_key'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_role', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('baseline_spo2', sa.Integer(), nullable=True),
    sa.Column('baseline_heart_rate', sa.Integer(), nullable=True),
    sa.Column('baseline_systolic_bp', sa.Integer(), nullable=True),
    sa.Column('baseline_respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('patient_vitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('resp_rate', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('consciousness_level', sa.Enum('ALERT', 'CVPU', name='consciousnesslevel'), nullable=False),
    sa.Column('oxygen_supplement', sa.Boolean(), nullable=False),
    sa.Column('spo2_scale', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('external_value', sa.Text(), nullable=True),
    sa.Column('internal_value', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issue_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWED', 'RESOLVED', 'IGNORED', name='issue_status_enum'), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('clinical_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskband'), nullable=False),
    sa.Column('operational_priority', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['scoring_policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('partner_hospital_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='transferrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_hospital_id'], ['partner_hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_escalations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('from_role', sa.String(length=50), nullable=True),
    sa.Column('to_role', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='taskstatus'), nullable=False),
    sa.Column('assigned_to_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_row_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('source_bed_id', sa.Integer(), nullable=True),
    sa.Column('target_bed_id', sa.Integer(), nullable=True),
    sa.Column('partner_hospital_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='recommendationstatus'), nullable=False),
    sa.Column('recommendation_type', sa.Enum('LOCAL_ICU_TRANSFER', 'INTER_HOSPITAL_TRANSFER', 'CHAINED_TRANSFER', name='recommendationtype'), nullable=False),
    sa.Column('chained_patient_id', sa.Integer(), nullable=True),
    sa.Column('chained_target_bed_id', sa.Integer(), nullable=True),
    sa.Column('criticality_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('actioned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chained_patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chained_target_bed_id'], ['beds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_hospital_id'], ['partner_hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_bed_id'], ['beds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_bed_id'], ['beds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_record_id', sa.Integer(), nullable=False),
    sa.Column('parameter_breakdown', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['score_record_id'], ['score_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('score_record_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.Enum('USEFUL', 'TOO_SENSITIVE', 'TOO_LATE', 'INCORRECT_BASELINE', 'ALREADY_REVIEWED', 'NEEDS_ESCALATION', name='feedbacktype'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_record_id'], ['score_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_feedback')
    op.drop_table('score_explanations')
    op.drop_table('recommendations')
    op.drop_table('import_errors')
    op.drop_table('clinical_tasks')
    op.drop_table('alert_escalations')
    op.drop_table('transfer_requests')
    op.drop_table('score_records')
    op.drop_table('reconciliation_issues')
    op.drop_table('patient_vitals')
    op.drop_table('patient_baselines')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_integration_logs_idempotency_key'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_table('integration_api_keys')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_external_id_mappings_external_patient_code'), table_name='external_id_mappings')
    op.drop_table('external_id_mappings')
    op.drop_table('clinical_events')
    op.drop_table('beds')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_wards_name'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scoring_policies')
    op.drop_table('response_sla_policies')
    op.drop_table('patients')
    op.drop_table('partner_hospitals')
    op.drop_table('integrations')
    op.drop_table('idempotency_keys')
    op.drop_table('data_quality_issues')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
